services:
  server:
    image: nitz/java
    build: java/
    ports:
      - '9000:9000'
    deploy:
      resources:
        limits:
          memory: 200M
    restart: always

  monitor:
    image: nitz/python
    build: python/
    command: "python main.py monitor"
    depends_on:
      - server
    volumes:
      - ./python/output:/output

  stress:
    image: nitz/python
    build: python/
    command: "python main.py stress -a 20"
    depends_on:
      - server
