services:
  server:
    image: nitz/java
    build: server/
    ports:
      - '9000:9000'
    deploy:
      resources:
        limits:
          memory: 200M
    restart: always

  sampler:
    image: nitz/python
    build: sampler/
    depends_on:
      - server
    volumes:
      - ./sampler/output:/output
